### ISSUE TITLE
Error when running the preinstall.js and postinstall.js

### ISSUE THREAD

**Issue by Spenstar** [NativeScript/template-drawer-navigation-ng#52]
After cloning the template and running `npm i` I get the following output/error:
```console
> tns-template-drawer-navigation-ng@3.2.0 preinstall /Users/username/template-drawer-navigation-ng
> node tools/preinstall.js

preinstall script running...
creating /Users/username/tslint.json...
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-EvlaMH1YNSB1oEkHuErIvpisAS8= integrity checksum failed when using sha1: wanted sha1-EvlaMH1YNSB1oEkHuErIvpisAS8= but got sha512-9jjUFbTPfEy3R/ad/2oNbKtW9Hgovl5O1FvFWKkKblNXoN/Oou6+9+KKohPK13Yc3/TyunyWhJp6gvRNR/PPAw==. (8671 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-bWDjSzq7yDEwYsO3mO+NkBoHrzw= integrity checksum failed when using sha1: wanted sha1-bWDjSzq7yDEwYsO3mO+NkBoHrzw= but got sha512-pNgbURSuab90KbTqvRPsseaTxOJCZBD0a7t+haSN33piP9cCM4l0CqdzAif2hUqm716UovKB2ROmiabGAKVXyg==. (5398 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> nativescript-telerik-ui@3.1.1 preinstall /Users/username/template-drawer-navigation-ng/node_modules/nativescript-telerik-ui
> node ./scripts/eula-prompt.js

Progress NativeScript UI Free is licensed under the Telerik End User License Agreement for UI for NativeScript Free: http://www.telerik.com/purchase/license-agreement/ui-for-nativescript-free

> node-sass@4.5.3 install /Users/username/template-drawer-navigation-ng/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/username/.npm/node-sass/4.5.3/darwin-x64-57_binding.node

> node-sass@4.5.3 postinstall /Users/username/template-drawer-navigation-ng/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/username/template-drawer-navigation-ng/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> nativescript-angular@4.2.0 postinstall /Users/username/template-drawer-navigation-ng/node_modules/nativescript-angular
> node postinstall.js


> nativescript-dev-sass@1.3.2 postinstall /Users/username/template-drawer-navigation-ng/node_modules/nativescript-dev-sass
> node postinstall.js


> nativescript-dev-typescript@0.5.0 postinstall /Users/username/template-drawer-navigation-ng/node_modules/nativescript-dev-typescript
> node postinstall.js

Hook already installed: nativescript-dev-typescript
Hook already installed: nativescript-dev-typescript
Hook already installed: nativescript-dev-typescript
Adding 'es6' lib to tsconfig.json...
Adding 'dom' lib to tsconfig.json...
Adding 'es2015.iterable' lib to tsconfig.json...
Adding tns-core-modules path mappings lib to tsconfig.json...
Project already targets TypeScript 2.5.2

> tns-template-drawer-navigation-ng@3.2.0 postinstall /Users/username/template-drawer-navigation-ng
> node tools/postinstall.js

postinstall script running...
{ Error: Cannot find module '/Users/username/package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at getAppRootFolder.then (/Users/username/template-drawer-navigation-ng/tools/postinstall.js:30:33)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
Removing tools directory...
npm notice created a lockfile as package-lock.json. You should commit this file.
added 230 packages in 10.35s
```
It looks like it goes one directory back too far.

**Comment by borisKarastanev** [comment]
Hi @Spenstar ,
Thank you for submitting the issue. 

In order to create an app with one of our templates you need to use the NativeScript CLI by running the following command:  ` tns create yourAppName --template tns-template-drawer-navigation-ng`

This will create a **yourAppName** directory with all the necessary files to successfully run the  tns-template-drawer-navigation-ng app template. 

For more information, please read the repository [README](https://github.com/NativeScript/template-drawer-navigation-ng/blob/master/README.md) and if you have more question, do not hesitate to contact us. 

Best regards,
The NativeScript Templates Team

**Comment by Spenstar** [comment]
Ahh, thanks.
