### ISSUE TITLE
Postinstall script failed

### ISSUE THREAD

**Issue by hackerunet** [NativeScript/template-drawer-navigation-ng#87]
After npm install I got this error and this are my system details:

node -v v9.6.1
npm -v 5.6.0
tsc -v Version 2.7.2
Python 2.7.12

```
> node postinstall.js

Creating file: /home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/webpack.config.js
Creating file: /home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/app/vendor-platform.android.ts
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/app/vendor-platform.android.ts'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at copyTemplate (/home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/node_modules/nativescript-dev-webpack/projectFilesManager.js:79:12)
    at /home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/node_modules/nativescript-dev-webpack/projectFilesManager.js:44:9
    at Array.forEach (<anonymous>)
    at Object.addProjectFiles (/home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/node_modules/nativescript-dev-webpack/projectFilesManager.js:42:31)
    at Object.install (/home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/node_modules/nativescript-dev-webpack/installer.js:14:25)
    at Object.<anonymous> (/home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/node_modules/nativescript-dev-webpack/postinstall.js:12:15)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
npm WARN schema-utils@0.4.3 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-dev-webpack@0.9.2 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-dev-webpack@0.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by manoldonev** [comment]
Does shorter name for the template install path make any difference i.e. `/home/hackerunet/Documentos/projects/amicasa/mx-amicasa/template-drawer-navigation-ng/` - > `/home/hackerunet/test/template-drawer-navigation-ng/`?

**Comment by hackerunet** [comment]
No changes, still the same issue. but I try using tns create app instead and worked without issues.

**Comment by manoldonev** [comment]
@hackerunet As noted in the [readme](https://github.com/NativeScript/template-drawer-navigation-ng/edit/master/README.md) you should create app from the template either via: `tns create my-app-name --template tns-template-drawer-navigation-ng` (uses npm published version of the template) or `tns create my-app-name --template https://github.com/NativeScript/template-drawer-navigation-ng (uses master branch of the template)`. You should not clone the repo and run `npm install` on it -- it will not work.
